galaxy_info:
  role_name: preconfig
  description: Настройка серверов для работы с LAMP
  author: Магомедов Магомед
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - all
